version: '3.8'

services:
  app:
    image: tryhardbich/devops-for-developers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: ["npm", "test"]
    environment:
      - NODE_ENV=test
